
spring:
  profiles:
    active: default,dev
  datasource:
    hikari:
      minimum-idle: 20
      maximum-pool-size: 100
  flyway:
    baseline-version: 1
    validate-on-migrate: false
  application:
    name: docker-admin
